### ISSUE TITLE
Latest propka no compatible with MDA < 1.0: AttributeError: 'PropkaTraj' object has no attribute 'times'

### ISSUE THREAD

**Issue by WillPPK** [Becksteinlab/propkatraj#32] opened 2020-11-12 18:17 UTC
I have recieved an error message when I run pkatraj.run(verbose=True, start=300, stop=500, step=20).

I have checked the trajectory and they are all fine. Not too sure what's going on..

AttributeError                            Traceback (most recent call last)
<ipython-input-23-2189a5adf251> in <module>
----> 1 pkatraj.run(verbose=True, start=300, stop=500, step=20)

~/.local/lib/python3.7/site-packages/MDAnalysis/analysis/base.py in run(self, start, stop, step, verbose)
    198             self._pm.echo(self._frame_index)
    199         logger.info("Finishing up")
--> 200         self._conclude()
    201         return self
    202 

~/anaconda3/lib/python3.7/site-packages/propkatraj/propkatraj.py in _conclude(self)
    226         logging.warning(wmsg)
    227 
--> 228         self.pkas = pd.DataFrame(self._pkas, index=pd.Float64Index(self.times,
    229                                  name='time'), columns=self._columns)

Thank you so much for your help in advance.

Best wishes

Will

**Comment by IAlibay** [comment] 2020-11-12 18:26
@WillPPK could you confirm what eversion of MDAnalysis and propka you are running?

<s>Also additional things like python version could be useful here.</s> (edit; nevermind it's in the trace)

**Comment by WillPPK** [comment] 2020-11-12 18:55
@IAlibay MDAnalysis - 0.20.1
propka - 3.1.0

Thank you so much

Will

**Comment by IAlibay** [comment] 2020-11-12 18:58
I suspect the issue is that we are accessing `AnalysisBase` attributes that only exist in MDAnalysis 1.0+

@WillPPK could you try again using an install that uses MDAnalysis 1.0 instead?

**Comment by WillPPK** [comment] 2020-11-12 19:11
Yes - that works now. Thank you so much.

**Comment by IAlibay** [comment] 2020-11-12 19:35
Fix here should be just to pin the MDAnalysis version to `>1.0,<2.0` in setup.py (for a python 2.7-inclusive release, otherwise we can drop `<2.0`). I'll open up a PR.

Maybe combined with an appropriate fix for https://github.com/jensengroup/propka/issues/98 and #31 we could push this as a minor bugfix update? Thoughts @orbeckst ?

**Comment by orbeckst** [comment] 2020-11-13 00:28
I'm happy with a patch release – "release early and often". Thank you for keeping an eye on things!!

**Comment by IAlibay** [comment] 2023-02-03 21:08
Fixed via #34

**Closed as completed by IAlibay** 2023-02-03 21:08 UTC
